#include<iostream>
#include<cmath>

using namespace std;

int main(){
    /*double a;
    double b;
    double c;
    cout << "Enter input for A : " << a ;
    cin >> a;
    cout << "Enter input for B : " << b ;
    cin >> b;
    a = pow (a , 2);
    b = pow (b , 2);
    c =sqrt( a + b );
    cout << "C: " << c ;
    return 0;*/

    int grade ;
    cout << "Enter students Grade: ";
    cin >> grade ;


    switch (grade)
    {
    case A:
        cout << " You did great!";
        break;
    
    default:
        break;
    }


    
}